# Generated by Django 4.0.6 on 2022-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='foregin_pop',
        ),
        migrations.RemoveField(
            model_name='pop',
            name='foregin_category',
        ),
        migrations.RemoveField(
            model_name='pop',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Pop',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
