# Generated by Django 4.0.6 on 2022-07-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_pop_foregin_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pop',
            name='foregin_category',
        ),
    ]
