# Generated by Django 4.0.6 on 2022-07-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_category_list'),
        ('profiles', '0005_remove_pop_foregin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='foregin_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
