# Generated by Django 4.0.6 on 2022-07-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_pop_foregin_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pop',
            old_name='foregin_category',
            new_name='foreign_category',
        ),
    ]
