# Generated by Django 4.0.6 on 2022-07-26 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_rename_foregin_category_pop_foreign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='user_who_like',
            field=models.ManyToManyField(related_name='user_who_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
