# Generated by Django 4.0.6 on 2022-07-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_pop_user_who_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='pop_image',
            field=models.ImageField(blank=True, null=True, upload_to='popimg'),
        ),
    ]
