# Generated by Django 4.0.6 on 2022-07-28 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_pop_save_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
