# Generated by Django 4.0.6 on 2022-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='promise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default='비밀번호 재확인', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='비밀번호 입력', max_length=12),
        ),
    ]
